sequenceDiagram
	Participant User
	Participant Application(Web or Native)
	Participant Web Application Server
	Participant Database
	User ->> Application(Web or Native): Opens application
	Application(Web or Native) -->> Web Application Server: Root page request
	Web Application Server  -->> Application(Web or Native): React App is served
	Application(Web or Native) ->> Application(Web or Native): Check existance of JWT
	Application(Web or Native) ->> User: No JWT so show Login Page
	User ->> Application(Web or Native): Choose Forgot Password Link
	Application(Web or Native) ->> User: Show password reset page (which also asks token)
	Application(Web or Native) ->> Web Application Server: POST to /generateResetPwdToken
	Web Application Server ->> Web Application Server: Lock Control
	Web Application Server -> Database: Check if requester email exists
	Web Application Server ->> Web Application Server: Generate verification token
	Web Application Server -> Database: Save verification token
	Web Application Server ->> Web Application Server: Generate reset password JWT
	Web Application Server -->> User: Send verification token via email
	Web Application Server ->> Application(Web or Native): Send reset password JWT
	User ->> Application(Web or Native): Paste the verification token
	User ->> Application(Web or Native): Provide new password
	Application(Web or Native) ->> Web Application Server: /resetPwd with reset pasword JWT, verification token and new password
	Web Application Server ->> Web Application Server: Check lock
	Web Application Server ->> Web Application Server: Extract JWT from Authorization header
	Web Application Server ->> Web Application Server: Verify JWT
	Web Application Server ->> Web Application Server: Check lock
	Web Application Server -> Database: Get saved token
	Web Application Server -> Web Application Server: Check saved token vs posted token and the expiration
	Web Application Server -> Web Application Server: Check strength of new password
	Web Application Server ->> Web Application Server: Hash new password
	Web Application Server -> Database: Update saved hashed password
	Web Application Server ->> Web Application Server: Generate login JWT
	Web Application Server ->> Application(Web or Native): JWT
	Application(Web or Native) ->> Application(Web or Native): Save JWT
