sequenceDiagram
	Participant User
	Participant Application(Web or Native)
	Participant Web Application Server
	Participant Database
	User ->> Application(Web or Native): Opens application
	Application(Web or Native) -->> Web Application Server: Root page request
	Web Application Server  -->> Application(Web or Native): React App is served
	Application(Web or Native) ->> Application(Web or Native): Check existance of JWT
	Application(Web or Native) ->> User: No JWT so show Login Page
	User ->> Application(Web or Native): Provides username and password
	Application(Web or Native) ->> Web Application Server: /login
	Web Application Server -> Database: Get hashed password using email
	Web Application Server ->> Web Application Server: Bcrypt compare hashed password with saved hash
	Web Application Server ->> Web Application Server: If comparison is successfull reset lock counters
	Web Application Server ->> Web Application Server: Generate JWT using the email
	Web Application Server ->> Application(Web or Native): JWT
	Application(Web or Native) ->> Application(Web or Native): Save JWT
