sequenceDiagram
	Participant User
	Participant Application(Web or Native)
	Participant Web Application Server
	Participant Database
	Participant SPA Website or App Marketplaces
	User --> SPA Website or App Marketplaces: Get the native or web app
	SPA Website or App Marketplaces --> Application(Web or Native): App is placed
	Application(Web or Native) --> Application(Web or Native): ...
	Application(Web or Native) ->> Application(Web or Native): Confirm existance of JWT
	Application(Web or Native) ->> Web Application Server: /checkJWT
	Web Application Server ->> Web Application Server: Check lock controls
	Web Application Server ->> Web Application Server: Extract Authorization header
	Web Application Server ->> Web Application Server: Verify JWT
	Web Application Server ->> Web Application Server: If JWT is not valid increment lock counter
	Web Application Server ->> Application(Web or Native): Respond JWT and result
	Application(Web or Native) ->> Application(Web or Native): Decide next page according to JWT result
