sequenceDiagram
	Participant User
	Participant Application(Web or Native)
	Participant Web Application Server
	Participant Database
	User -> Application(Web or Native): ...
	Application(Web or Native) ->> User: Show Change Password Page
	User ->> Application(Web or Native): Provide new password
	Application(Web or Native) ->> Web Application Server: /updatePassword
	Web Application Server ->> Web Application Server: Check lock control
	Web Application Server ->> Web Application Server: Check password strength
	Web Application Server ->> Web Application Server: Check JWT and extract email
	Web Application Server ->> Web Application Server: Hash new password
	Web Application Server ->> Database: Update hashed password
	Web Application Server ->> Application(Web or Native): Send result
